name: admin_bpjs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Icon Style iOS
  cupertino_icons: ^1.0.8

  # Penyimpanan Sederhana (Shared Preferences)
  shared_preferences: ^2.2.2

  # Database SQL (Jika ingin pakai database komplek)
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Pendukung SQL untuk Windows/Desktop (Opsional)
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true